[package]
name = "leptos_animation"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
leptos = { git = "https://github.com/leptos-rs/leptos.git", rev = "c55067a", features = [
    "stable",
] }

instant = { version = "0.1.12", features = ["wasm-bindgen"] }
